# Generated by Django 5.1 on 2024-09-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='receipe_instructions',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='receipe',
            name='receipe_description',
            field=models.TextField(max_length=1000),
        ),
    ]
