# Generated by Django 5.1 on 2024-09-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_receipe_receipe_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='receipe_image',
            field=models.ImageField(upload_to='receipes'),
        ),
    ]
